Add support for automatic ACL config sync
PayU/redis-operator pull request #107
Opened 2021-07-01 09:59 UTC by voltbit

- Added a controller for ACL and redis.cli config maps
- Added functionality for quickly propagating the ACL config changes to
all nodes
- Refactored the code of the redis cluster controller - moved all the
state handlers from helpers.go to rediscluster_controller.go
- Improved the handling of ACL commands in the rediscli wrapper - added
string conversions to help with hashing
- Added a dev mode flag to the Golang module for better debug messages

2021-07-05 13:10 UTC, voltbit commented
| Test | Time | Data/node |
| --- | --- | --- |
| TestRollingUpdate | 328.142s | 1.9GB |
tested on:
K8s `v1.19.11`
Linux `5.10.46`
`cgroupsV2`

2021-07-06 11:28 UTC, shyimo requested changes
Overall except the comments very good job ! 👍

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +			for dataKey := range configMap.Data {
you don't have to iterate over all the configmap data because you are looking for a specific key ("users.acl")
you can just do a simple if like
```
if users := configMap.Data["users.acl"]; users != "" {
 // logic here
}

i think this will make a next feature (listen for redis config change) much more easy to add (use another if or use switch case)
```

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +	}
looks to me that something is missing here. if you are using waiting group (wg) you usually wants to wait for all the goroutines inside the group will finish. i see that you are using `Add` for each pod and also `defer wg.Done()` in each goroutine but i don't see wg.Wait() usage (i expected to find it here, right before the `if syncFail`)

let me know if i missed something

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +const ACLFilePropagationDuration time.Duration = time.Millisecond * 5000
hard coded value can be a bit problematic here. we can use 5000 as default value but i think we need to except this option from env variable as well. i'm not familier with kubelet sync time on hosts. this can be effected from many paramaters i assume. so in case 5000 will not do the trick, i want to have the ability to change env variable and not touch the source code

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +func (r *RedisConfigReconciler) syncConfig(latestConfigHash string, redisPods ...corev1.Pod) error {
redisPods is not a slice of pods. it's just a single pod 
you are calling this function (line 181 for example) like this:
`if err := r.syncConfig(configMapACLHash, *pod); err != nil {`

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +	for _, pod := range redisPods {
same as above, not sure what on what you iterate here, cause redisPods is actually a single pod

2021-07-06 11:28 UTC, shyimo commented on controllers/config_controller.go
> +func (r *RedisConfigReconciler) updateACLHashStatus(status string, redisPods ...corev1.Pod) error {
function signature looks weird. i didn't find any place in the code you are calling it with multiple pods, only 1

2021-07-06 11:57 UTC, voltbit commented on main.go
> +	retryLockDuration := 4 * time.Second
I noticed that the K8s API was sending a message to all configmap controllers every time the configmap used for getting the lock was accessed. When the operator instances try to aquire the lock, the the K8s API will notify all configmap watchers. This happens every two seconds.
I decreased the value to 4 seconds only because of that - to reduce the noise and potential load on the K8s API. From my tests the leader election setup is not very fast anyway, I dont think you will notice a difference between 2 and 4 seconds.

2021-07-06 11:58 UTC, voltbit commented on controllers/config_controller.go
> +	}
Yeah I totally missed the wait, thanks for catching this :+1:

2021-07-06 12:14 UTC, voltbit commented on controllers/config_controller.go
> +const ACLFilePropagationDuration time.Duration = time.Millisecond * 5000
I agree, but this change has to be made globally, to all our hardcoded times.
https://github.com/PayU/redis-operator/blob/7ba523f3e9540f358764586b8ff3c6c13c5456e4/controllers/helpers.go#L13-L22
I suggest we make the operator use a configuration file where all these are set.

2021-07-06 12:21 UTC, voltbit commented on controllers/config_controller.go
> +func (r *RedisConfigReconciler) syncConfig(latestConfigHash string, redisPods ...corev1.Pod) error {
That is just how variadic params work, it is a slice or nil.
https://golang.org/ref/spec#Passing_arguments_to_..._parameters

2021-07-06 12:21 UTC, voltbit commented on controllers/config_controller.go
> +	for _, pod := range redisPods {
https://github.com/PayU/redis-operator/pull/107#discussion_r664504099

2021-07-06 12:22 UTC, voltbit commented on controllers/config_controller.go
> +func (r *RedisConfigReconciler) updateACLHashStatus(status string, redisPods ...corev1.Pod) error {
It is more for the sake of consistency, many methods have variadic params.

2021-07-08 08:34 UTC, shyimo commented on controllers/config_controller.go
> +const ACLFilePropagationDuration time.Duration = time.Millisecond * 5000
sounds good. we can add an issue of that

2021-07-08 08:36 UTC, shyimo commented on controllers/config_controller.go
> +	https://raw.githubusercontent.com/antirez/redis/6.2.0/redis.conf
any concerns on that one ?

2021-07-08 08:38 UTC, shyimo commented on controllers/config_controller.go
> +func (r *RedisConfigReconciler) syncConfig(latestConfigHash string, redisPods ...corev1.Pod) error {
yes, i understand  how variadic params works. but i think in our case there is no use case for that (also in the future) to pass more then 1 pod because of the main loop. but i don't mind keeping it like this, it does not harm.
approved

2021-07-08 08:41 UTC, shyimo approved these changes

2021-07-08 08:42 UTC, merged