Horizontal scale
PayU/redis-operator pull request #134
Opened 2022-06-27 11:20 UTC by NataliAharoniPayu

2022-06-27 15:13 UTC, NataliAharoniPayu commented on controllers/operator_entrypoints_module.go
> +		return c.String(http.StatusOK, "Could not retrieve redis cluster view to")
typo, remove 'to' from message

2022-06-27 15:17 UTC, NataliAharoniPayu commented on controllers/operator_entrypoints_module.go
> +		reconciler.Log.Error(err, "Could not perform cluster fix")
logistical issue - after each fix it is recommended to run 'rebalance', we can reflect it in log or set the cluster state to 'rebalance' or do both by informing the user to pay attention that rebalance takes action in next reconcile loop, if it didn't  - suggest to run it manually with /rebalance

2022-06-27 19:20 UTC, shyimo requested changes
I think you did an amazing job so far. wall done @NataliAharoni99.

i try to tackle the operator in various way and all worked well. the code also looks really good in general and i don't have a lot of comments (which is usually not the case :) )

2022-06-29 18:03 UTC, voltbit commented on helm/values.yaml
> +  leaderCount: 5
Lets keep this setup small by default.

2022-06-29 18:03 UTC, voltbit commented on helm/values.yaml
> +  leaderFollowersCount: 2
Lets keep this setup small by default.

2022-06-29 18:05 UTC, voltbit commented on server/router.go
> +	e.POST("/upgrade", controllers.UpgradeCluster)
We need documentation for each endpoint.

2022-07-05 08:34 UTC, NataliAharoniPayu commented on main.go
> +		Cache:                 mgr.GetCache(),
It was used for a practice i considered worth to have - 'block' the k8s api request for pod list until cache is synced (wait for k8s cache sync is a method cache object has), eventually a different practice was chosen: to have the request on time and wait for terminating pods if appeared during pod status analyze. 
as i see it, the second choice is covering better the range of cases that requires waiting prior to operator action.
im removing those to lines.

2022-07-05 16:49 UTC, NataliAharoniPayu commented on server/router.go
> +	e.POST("/populateMockData", controllers.PopulateClusterWithMockData)
A 'setter' variable been added to the operator config, named 'ExposeSensitiveEntryPoints', it is set defaultly to false, and indicates the operator rather or not to allow the continuity of sensitive flows origined from all the sensitive entry points: 
* Cluster reset
* Cluster flush all data
* Cluster populate with mock data
* Cluster test with mock data

2022-07-06 10:30 UTC, NataliAharoniPayu commented on helm/values.yaml
> +  leaderFollowersCount: 2
will do

2022-07-10 10:09 UTC, closed without merging